### ISSUE TITLE
`java.lang.ClassCastException` when setting background handler on Android

### ISSUE THREAD

**Issue by mbabker** [fluttercommunity/flutter_uploader#166]
When my app is making the `FlutterUploader().setBackgroundHandler()` call, it's triggering a `java.lang.ClassCastException` on Android because an Integer cannot be cast to Long.

```sh
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.bluechilli.flutteruploader.MethodCallHandlerImpl.setBackgroundHandler(MethodCallHandlerImpl.java:80)
	at com.bluechilli.flutteruploader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:56)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

This is with 3.0.0-beta.1 of this package running on an Android 11 emulator using Flutter 2.0.6 from the stable channel.

**Comment by lyio** [comment]
What a strange issue.

I don't see anything wrong with your suggestion.

It might also be possible to use `Number` instead of `Long` and then call `longValue()` on it. 

```java
  void setBackgroundHandler(MethodCall call, MethodChannel.Result result) {
    Number callbackHandle = call.argument("callbackHandle");
    if (callbackHandle != null) {
      SharedPreferenceHelper.saveCallbackDispatcherHandleKey(context, callbackHandle.longValue());
    }

    result.success(null);
  }
```
