### ISSUE TITLE
Android 12: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified

### ISSUE THREAD

**Issue by ghunkins** [fluttercommunity/flutter_uploader#216]
### Issue

**Targeting Android SDK 31+ results in immediate crashing for deployments to Android 12+.**

### Stack Trace

```
Fatal Exception: java.lang.IllegalArgumentException: com.example.example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
       at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
       at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
       at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

### StackOverflow

[https://stackoverflow.com/a/70227216](https://stackoverflow.com/a/70227216)

### Diagnosis

Currently this package relies on:

```
implementation 'androidx.work:work-runtime:2.5.0'
```

We need to upgrade this to the fixed:

```
implementation 'androidx.work:work-runtime:2.7.1
```

**If you are dealing with this and need this fixed prior to the release of a fix:**

(1) Open `android/app/build.gradle`

(2) Add the below line within `dependencies`:

```
implementation "androidx.work:work-runtime:2.7.1"
```

i.e.

```
dependencies {
    ...
    implementation "androidx.work:work-runtime:2.7.1"
}
```

**Comment by orestesgaolin** [comment]
Thanks for the solution!
