### ISSUE TITLE
Get an error in android while debugging app

### ISSUE THREAD

**Issue by lkrjangid1** [fluttercommunity/flutter_uploader#237]
```

I/WM-WorkerWrapper(23543): Worker result SUCCESS for Work [ id=1ad23ee6-f3d7-4c1f-bf45-b1fb84841b5b, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ]
E/flutter (23543): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (23543): java.net.ProtocolException: unexpected end of stream
E/flutter (23543): ^
E/flutter (23543):
E/flutter (23543): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (23543): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter (23543): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter (23543): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter (23543): #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter (23543): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (23543): #6      backgroundHandler.<anonymous closure>
E/flutter (23543): #7      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #13     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #15     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #22     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #23     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (23543): #28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (23543): #29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (23543): #30     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (23543): #31     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #32     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #34     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (23543): #35     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23543): #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23543):
E/flutter (23543): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (23543): There are no items to upload
E/flutter (23543): ^
E/flutter (23543):
E/flutter (23543): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (23543): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter (23543): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter (23543): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter (23543): #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter (23543): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (23543): #6      backgroundHandler.<anonymous closure>
E/flutter (23543): #7      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #13     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #15     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #22     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #23     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (23543): #28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (23543): #29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (23543): #30     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (23543): #31     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #32     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #34     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (23543): #35     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23543): #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23543):
E/flutter (23543): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (23543): java.net.ProtocolException: unexpected end of stream
E/flutter (23543): ^
E/flutter (23543):
E/flutter (23543): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (23543): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter (23543): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter (23543): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter (23543): #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter (23543): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (23543): #6      _FrontPageChatsState.flutterUploadProgressAndStatusListen.<anonymous closure>
E/flutter (23543): #7      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #13     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #15     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #22     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #23     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[log] refreshChannelPage
E/flutter (23543): #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (23543): #28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (23543): #29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (23543): #30     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (23543): #31     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #32     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #34     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (23543): #35     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23543): #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[log] refreshChannelPage
E/flutter (23543):
E/flutter (23543): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (23543): There are no items to upload
E/flutter (23543): ^
E/flutter (23543):
E/flutter (23543): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (23543): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter (23543): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter (23543): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter (23543): #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter (23543): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (23543): #6      _FrontPageChatsState.flutterUploadProgressAndStatusListen.<anonymous closure>
E/flutter (23543): #7      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #13     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #15     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23543): #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23543): #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (23543): #22     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23543): #23     _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (23543): #24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23543): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23543): #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23543): #27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (23543): #28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (23543): #29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (23543): #30     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (23543): #31     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #32     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #34     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (23543): #35     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23543): #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23543): #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23543): #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23543): #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23543):
```

**Comment by ened** [comment]
Looks like the server did not respond with a valid JSON.
