### ISSUE TITLE
Failed to upload on large mp4 file. 'code: upload_task_error, error: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL'

### ISSUE THREAD

**Issue by rynhrn** [fluttercommunity/flutter_uploader#97]
I get this error when uploading a relatively large MP4 file (~100/200mb). Sometimes it would happen nearing the end of upload or 1/4 of the way through it, but it happens regardless. The device I'm using is Samsung Galaxy S8 running Android version 9. Have not been able to test on an iOS device so not sure if it happens on those. Using the latest version of flutter_uploader too (1.2.0).

Code to replicate

```dart
Future<void> _uploadFile() async {
    final String _token = await LocalStorage.getAuthToken();

    _uploaderTask = await uploader.enqueue(
        url: URL,
        files: <FileItem> [
          FileItem(
            filename: path.basename(file.path),
            savedDir: path.dirname(file.path),
            fieldname: 'attachment',
          ),
        ],
        method: UploadMethod.POST,
        headers: <String, String> {
          'Authorization': _token, 
          'Accept': 'application/json',
          'Content-Type': 'multipart/form-data; boundary=WebAppBoundary'
        },
        tag: 'upload ${task.id}',
      );

      _progressSubscription = uploader.progress.listen((UploadTaskProgress progress) {
        setState(() => _uploadProgress = (progress.progress / 100).toDouble() );
      });

      _resultSubscription = uploader.result.listen((UploadTaskResponse result) async {
        setState(() {
          _isUploading = false;
          _isCompleted = true;
        });
      }, 
      onError: (Object error, StackTrace stackTrace) {
        print('ERORR: ${error.toString()}');
        print('STACK TRACE: ${stackTrace.toString()}');
        setState(() {
          _isUploading = false;
          _hasError = true;
        });
      });
}
```

The console output after upload stops

```
D/UploadWorker(11469): UploadWorker - Stopped
D/UploadWorker(11469): Failed to upload - taskId: 99f16347-deb7-4f58-ac7d-fac60462d903, code: upload_task_error, error: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
I/chatty  (11469): uid=10590(com.example.recapchat) pool-1-thread-4 identical 41 lines
D/UploadWorker(11469): Failed to upload - taskId: 99f16347-deb7-4f58-ac7d-fac60462d903, code: upload_task_error, error: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
I/WM-WorkerWrapper(11469): Work [ id=99f16347-deb7-4f58-ac7d-fac60462d903, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ] was cancelled
I/WM-WorkerWrapper(11469): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(11469): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper(11469): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper(11469): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper(11469): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
I/WM-WorkerWrapper(11469): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
I/WM-WorkerWrapper(11469): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/WM-WorkerWrapper(11469): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/WM-WorkerWrapper(11469): 	at java.lang.Thread.run(Thread.java:764)
```

Would appreciate any help with this. Thanks!

**Comment by kadnan0900** [comment]
@rynhrn
Hi,
can i use the library in production app Is it that much stable or not ?

**Comment by ened** [comment]
@rynhrn I've seen issues like that on S7 and S8 devices in the past. When the WiFi signal is being used like this, the connection may become unstable.

Unfortunately there is not too much we can do except retrying the upload.

Alternatively, you could try to upload the file in chunks and let the server put it back together.

Please try using the latest beta version of the plugin as well and open a new ticket if you can pin it to a configuration / setting in this plugin.

**Comment by stackved** [comment]
I was facing the same issue. I have fixed it. It happens on Android due to constraint on android's work manager. It is allowed to run only for sharp 10 minutes. Can I please take this up ? 

I want to contribute to open source.. first timer.
